### ISSUE TITLE
Feature request: support Syncthing

### ISSUE THREAD

**Issue by alexlyzhov** [kometenstaub/obsidian-version-history-diff#16]
I use Syncthing to sync vault but unfortunately it's always malfunctioning without a clear reason and creating conflict files like `Scratchpad.sync-conflict-20230112-003022-FUKIKK4.md` out of `Scratchpad.md`. I then have to review the conflicts one by one with an external tool (Meld) which is a bit unwieldy. I'd find much use out of an in-Obsidian review feature!

**Comment by kometenstaub** [comment]
I don't have plans to support that.

This plugin was created for your use case:
https://github.com/obsidianmd/obsidian-releases/pull/1621

https://github.com/friebetill/obsidian-file-diff
