### ISSUE TITLE
git diff view panel display exception

### ISSUE THREAD

**Issue by ku-zhen** [kometenstaub/obsidian-version-history-diff#17]
hello，I dont know why that occurs， I tried to solve it by myself, but in vain，please help me，thanks.

As you can see from the screenshot, there is a large blank in the middle：

![image](https://user-images.githubusercontent.com/61906420/212799486-e8ab9d67-655c-4141-b5a1-c71a29e1134a.png)

**Comment by kometenstaub** [comment]
Does it happen with the default theme? If not, then it is a CSS issue of the theme you're using.

**Comment by kometenstaub** [comment]
Closed for inactivity.
