### ISSUE TITLE
[Bug] There is no git diff history

### ISSUE THREAD

**Issue by fzyzcjy** [kometenstaub/obsidian-version-history-diff#26]
Hi thanks for the tool! I come from the recommendation in https://github.com/denolehov/obsidian-git, and want to display git history of a md file. However, as shown in the screenshot below, even though it has a lot of history git commits, it only shows one.

![image](https://github.com/kometenstaub/obsidian-version-history-diff/assets/5236035/b6f8240d-2d69-47af-aafa-b4cebaf20891)

**Comment by fzyzcjy** [comment]
I see: After upgrading obsidian-git it works!

**Comment by marchy** [comment]
@fzyzcjy how do you even invoke that window?

The README mentions "4. open a selected version in a modal" but I cannot for the life of me figure out how to do that (tried searching commands, opening the file in a new window and 'Open version history' from the right-click menu on the file but that shows local history only and not the diff view shown above)

**Comment by marchy** [comment]
UPDATE: Ahh found it!

![Image](https://github.com/user-attachments/assets/fce205e9-60c1-4a81-8310-1b7de2c7dc05)
