### ISSUE TITLE
First Two Characters of File Path Are Missing, Causing Errors (Show Git Diff view for active file)

### ISSUE THREAD

**Issue by peppermint1231** [kometenstaub/obsidian-version-history-diff#29]
Obsidian Git, version: 2.24.2
Version History Diff, version 2.2.0
Both are the latest versions.
The .git folder is located directly inside my vault.

- I am using version control with Obsidian Git without any issues.
- I am not using Sync.
- The command "Show File Recovery diff view for active file" works fine.
- The problem occurs only with the command "Show Git Diff view for active file."

# Error
When running the command "Show Git Diff view for active file" on the file Myvault/123456.md, an error popup appears along with the following console error:
![image](https://github.com/kometenstaub/obsidian-version-history-diff/assets/170179611/c770b015-b0b6-4833-ba03-20afe24e7777)

As you can see, the first two characters ("12") of the file path ("/123456.md") are missing, resulting in an error because "/3456.md" does not exist.

_**I conducted several experiments to investigate this issue.**_

## 1. Creating "/3456.md" and then running the command on "/123456.md":

![image](https://github.com/kometenstaub/obsidian-version-history-diff/assets/170179611/9c36152b-2a14-4b29-b0b6-c9ac2f4a95e1)
- The command executed but loaded "/3456.md".
- However, clicking on the version causes another error because two more characters are missing from the filename, resulting in an error that "/56.md" cannot be found.
![image](https://github.com/kometenstaub/obsidian-version-history-diff/assets/170179611/3bf6881c-1126-4064-80a9-41503d8c2d78)

## 2. Creating "xx123456.md" and then running the command:
- Similarly, it loaded "123456.md", but clicking on the version caused an error because "/3456.md" could not be found.
![image](https://github.com/kometenstaub/obsidian-version-history-diff/assets/170179611/945e73af-b2c6-4b3c-8377-5967f3312e11)
![image](https://github.com/kometenstaub/obsidian-version-history-diff/assets/170179611/41d9a7c1-d95f-47c8-bb31-9eae0f8c71f7)

---
**This issue occurs with all files in the vault that are already committed.**

For example, running the command on "/testfolder/123456.md" results in an error because the first two characters of the path ("te") are missing, leading to an error that "stfolder/123456.md" cannot be found.
![image](https://github.com/kometenstaub/obsidian-version-history-diff/assets/170179611/658df1d1-d39f-4f13-883c-50079ba92df6)

How can I resolve this issue?

**Comment by peppermint1231** [comment]
**+ I tried disabling/enabling the version history diff plugin, deleting/reinstalling it, all to no avail.**

**Comment by kometenstaub** [comment]
What are your Obsidian installer and app versions?
(Installer updates need to be made manually. If it’s not the latest, please update it.)

**Comment by peppermint1231** [comment]
> What are your Obsidian installer and app versions?
> (Installer updates need to be made manually. If it’s not the latest, please update it and see if the issue still occurs.)

If you're referring to the installer on the first install, the Obsidian installer is v1.5.12, and the current version is the same. latest.

**Comment by kometenstaub** [comment]
Has this issue always occurred or is this just happening now?

**Comment by peppermint1231** [comment]
> Has this issue always occurred or is this just happening now?

이 문제는 플러그인을 처음 사용했을 때부터 발생했다. (어제 처음으로 설치했다.)

**Comment by peppermint1231** [comment]
> Has this issue always occurred or is this just happening now? (Have you been using the plugin for some time already or did you just try it out.)

This issue has been happening since the first time I used the plugin (I installed it for the first time yesterday).

**Comment by kometenstaub** [comment]
I cannot reproduce the issue. I am on the early access version (same installer though), but that shouldn’t change anything. 

I don’t know what would cause this. 
I pass along the file path as I get it from Obsidian, and that part of the code has been the same for a long time.

**Comment by peppermint1231** [comment]
> I cannot reproduce the issue. I am on the early access version (same installer though), but that shouldn’t change anything.
> 
> I don’t know what would cause this. I pass along the file path as I get it from Obsidian, and that part of the code has been the same for a long time.

Thank you for reviewing this issue. I will also continue to investigate it further. Could you please tell me which file contains the code for retrieving the file path?

**Comment by kometenstaub** [comment]
https://github.com/kometenstaub/obsidian-version-history-diff/blob/82434693948eed67152cbd6e0c1216b2d5476337/src/main.ts#L30

https://github.com/kometenstaub/obsidian-version-history-diff/blob/82434693948eed67152cbd6e0c1216b2d5476337/src/git_diff_view.ts#L35

**Comment by kometenstaub** [comment]
If you figure out what the issue is, please let me know. Thanks!

**Comment by peppermint1231** [comment]
I just relaunched Obsidian after a long time, and I'm happy to see that the bug has been fixed with the latest update. While the cause is still unclear, it works perfectly in version 1.7.7. Thanks for your help!
