### ISSUE TITLE
`git obsidian error: fatal: path 'my-file-path' exists on disk, but not in '9b812828....'`

### ISSUE THREAD

**Issue by kometenstaub** [kometenstaub/obsidian-version-history-diff#7]
After renaming a file with `git mv`, clicking on an old version for getting the file content of that version yields this error. 

I would need a way to determine what the file name was before the renaming. The `git log` API does not provide any info concerning this. 

Fixing this should work by refactoring the git view to not work on file contents, and instead use the hashes to get the diffs.

cc @Vinzent03 - What is your take on that?

**Comment by kometenstaub** [comment]
The other thing that would need to be addressed is how to get the file content of a file that has been renamed. I have only been successful with `git show` when I used the old file name for an old commit. I've only tried it on the command line so far and didn't look into whether `simple-git` can deal with it.

**Comment by tim-hilde** [comment]
Any news on this?

**Comment by joellti** [comment]
Just wanted to voice my need of this being addressed since i refactor my notes quite often by moving them around and without this being addressed all the changes made to the notes before their last moves won't be displayed properly.

**Comment by Vinzent03** [comment]
@kometenstaub Hey I think I found a way to ship the old file name of a file with the result of the `log` method. This should help you right?

**Comment by kometenstaub** [comment]
@Vinzent03 If that means that I can call the API with the current file name and get contents from before the rename as well, yes.

**Comment by Vinzent03** [comment]
@kometenstaub `2.17.0` should now include the `fileName` parameter for each array element of the `log` result. You should be able to use that name with `git show` then.

**Comment by kometenstaub** [comment]
@Vinzent03 Thank you, I’ll look into it.
